### ISSUE TITLE
The images do not scale down

### ISSUE THREAD

**Issue by adrianmiu** [ivopetkov/responsively-lazy#1]
I don't know if this is intentional or not but when the screen goes from big to small and the "big" image was already loaded the "small" image is not loaded. I'm using quotes because I have the following scenario:
1. I use Bootstrap's grid feature on a website and I have a sidebar displayed for medium and large screens.
2. On small screens the sidebar is not displayed on the side so the main content area is bigger than on the medium screen. In this case I use bigger images but they are not loaded. 
I guess your library assumes that bigger images are for big screens and once you loaded the biggest image you don't need to load the smaller image.

**Comment by ivopetkov** [comment]
It's totally intentional. The idea is to save bandwidth because the big images can be scaled down by the browser.

**Comment by adrianmiu** [comment]
Yes, but the biggest image is not necessarily displayed on the biggest screen.
On a 768x1024 tablet I can display a 3 column grid (the image is 256px wide) and on a mobile phone I don't display a grid (the image is 320px wide).

**Comment by ivopetkov** [comment]
Can you please show us a demo of the issue.

**Comment by adrianmiu** [comment]
http://codepen.io/anon/pen/VLojzM
It works as expected. I misunderstood the format for the srcset

**Comment by ivopetkov** [comment]
In your code I see:

```
src="http://www.placehold.it/150x100"
data-srcset="http://www.placehold.it/450x300 450w, http://www.placehold.it/300x200 300w"
```

I'd recommend a higher-quality image in the src attribute as it's the one that's used as default image. For example, if the image container is 600px the default image will be loaded because there is no appropriate version described. It's better to load the 450x300 image than the 150x100 image.

This is the updated code:

```
src="http://www.placehold.it/450x300"
data-srcset="http://www.placehold.it/150x100 150w, http://www.placehold.it/300x200 300w"
```

**Comment by adrianmiu** [comment]
Ok, but the image provided in the `src` attribute is loaded by the browser so putting the biggest image there kind of defeats the purpose of the library.
Also, shouldn't the biggest container size in the srcset be used? Ie, use the 450w image for every container above 450px in width?

**Comment by ivopetkov** [comment]
Other lazy loading libraries tells you to put the smallest version in the `src` attribute. But this is exactly what is **different and cool** about Responsively Lazy.

The important part (that you've missed in your codepen) is the `srcset="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="` attribute. It prevents the image in the `src` attribute from loading. This works only in modern browsers. Old browsers show the image in the `src` attribute, and the library does not do anything there. Google and social networks also use the image in the `src` attribute, so it's better be high-resolution.
