### ISSUE TITLE
Retina images are loaded twice

### ISSUE THREAD

**Issue by phun-ky** [ivopetkov/responsively-lazy#11]
Maybe a dumb question, but why is the images in the `data-srcset` loaded twice?

**Comment by ivopetkov** [comment]
Why do you think it is loaded twice?

**Comment by phun-ky** [comment]
Because the Network tab indicates it:

![screenshot from 2016-08-25 10-50-04](https://cloud.githubusercontent.com/assets/1714029/17962556/bdfbd36e-6ab1-11e6-8080-97c75116ff8a.png)

The produced code from `responsively-lazy` (when images are loaded):

```
<img class="responsively-lazy" data-srcset="person.png?a5d4227fb0532c90a39d82c366e571a6 480w" src="person-min.png?5cf834969a2582645e2c547bb22bc33f" srcset="person.png?a5d4227fb0532c90a39d82c366e571a6">
```

The code in the html (before lazy loading):

```
<img class="responsively-lazy" src="person-min.png" data-srcset="person.png" srcset="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" />
```

**Comment by ivopetkov** [comment]
Can you please install v2.0.0 and try again.

**Comment by phun-ky** [comment]
I've already installed the latest from your git repo, and I still have
the same results.

**Comment by ivopetkov** [comment]
Can you please send me another screenshot of your Network tab and make the 4th column slightly bigger, so that the whole content is visible.

**Comment by phun-ky** [comment]
@ivopetkov Oh, dang. I didn't respond to this. :disappointed: , sorry :(

Here is the screenshot, this is from a "hard refresh"

![screenshot from 2017-03-02 12-47-06](https://cloud.githubusercontent.com/assets/1714029/23506042/78a63d34-ff46-11e6-83db-4424f78102d5.png)

soft refresh:

![screenshot from 2017-03-02 12-48-42](https://cloud.githubusercontent.com/assets/1714029/23506071/a488ac5c-ff46-11e6-8b6e-9e26a8463688.png)

**Comment by ymnj** [comment]
@phun-ky Where you able to solve this issue. I'm running into the same problem.

**Comment by phun-ky** [comment]
@ivopetkov  here is another example:

![screenshot from 2017-03-30 11-03-31](https://cloud.githubusercontent.com/assets/1714029/24496449/916dab06-1538-11e7-8a7c-f806fd4c8df6.png)

The `login.jpg` image is set as the src, blurry is set to `srcset` and `data-srcset` is `${login} 960w, ${login2} 1920w, ${login3} 3840w`

> Tbh, this `${login} 960w, ${login2} 1920w, ${login3} 3840w` should probably based on the correct sizes of the files: `${login} 1440w, ${login2} 2880w, ${login3} 4320w`

Same setup, different zoom:

![screenshot from 2017-03-30 11-06-13](https://cloud.githubusercontent.com/assets/1714029/24496582/f5787cf2-1538-11e7-9ded-173170fdd660.png)

I will add a video of the network tab so you can see. This video recording is from windows chrome, and I see that the second version of the same image are downloaded after the first version of the image is downloaded.

https://www.youtube.com/watch?v=sUSlBC8DbdY&feature=youtu.be


**ALL PROVIDED EXAMPLES ARE FROM LINUX CHROME UNLESS OTHER IS SPECIFIED**

In IE Edge, I get just the `login.jpg`. (as expected (?))


@ymnj have not solved this yet

**Comment by ivopetkov** [comment]
I wanted a screenshot with a larger 4th column, so it's clear who is the initiator of the requests. In your screenshots and video the values responsivelyLazy.js, preact.js, vendors.js and Other at shown. I'll review again the images loading code in Responsively Lazy, but I believe in this case the reason for double loading are the other libraries you use. I'd recommend a deeper dive into their's code to see what and why they do.

**Comment by phun-ky** [comment]
A side note: I think that the desired usage of this module is not quite compatible with a react + redux SPA, since it's not quite clear on how I can control the initialisation of the module.

But here's how I've set it up, and the culprit is the re-render, I assume:

I've created a component, [ResponsiveImage](https://gist.github.com/phun-ky/1d6d27559732b0269e7531b3a6b5e7c0), that takes in the required params to operate, and sets an `is-loaded` class to it via `setState`. This means that the order of what is happening in the last given scenario (one image) is like this:

1. Image renders
2. Image is loaded (downloaded and displayed)
2. onLoad is fired
3. setState sets className, forces a re-render
3. Image renders again
2. Image is loaded (downloaded and displayed)
2. onLoad is fired, nothing happens (since `imageLoaded` is not changed)

**EDIT:** with this screenshot, you see that it is responsively lazy that initiates it:
![screenshot from 2017-03-31 10-09-37](https://cloud.githubusercontent.com/assets/1714029/24542012/48ee2a82-15fa-11e7-9317-064e3ad768ea.png)

And it's referring to https://github.com/ivopetkov/responsively-lazy/blob/master/responsivelyLazy.js#L108 and https://github.com/ivopetkov/responsively-lazy/blob/master/responsivelyLazy.js#L119

**EDIT 2:** In light of the new screenshot above, it is unlikely that the culprit of this issue is react or the re-rendering of the component.  It is not the default browser behaviour to download an image with the same URL twice  or more if it exist in the DOM or in the cache. Even if you insert two DOM-nodes with the same image on the same time, the image is not downloaded twice. So it has to be something with the caching or that the module (responsively lazy) do something with the URLs. (Or downloaded in an other way than through DOM-nodes)

**Comment by ivopetkov** [comment]
Thanks. I think I have a solution. I'll write you back soon.

**Comment by ivopetkov** [comment]
I've made a fix. Can you please download the JS code from the master branch and test on your environment.

**Comment by phun-ky** [comment]
![screenshot from 2017-03-31 11-03-21](https://cloud.githubusercontent.com/assets/1714029/24543926/b8988588-1601-11e7-85a6-14c3dd8c40c7.png)

Looks much better! Please publish the fix to npm aswell ;)

**Comment by selbekk** [comment]
Great job guys :+1:

**Comment by ivopetkov** [comment]
v2.0.1 is on npm now.
