### ISSUE TITLE
Chrome and missing images on scrolling

### ISSUE THREAD

**Issue by dleer** [ivopetkov/responsively-lazy#12]
I've noticed an issue that seems limited to Chrome.   When scrolling a page of responsively-lazy images, sometimes the transparent placeholder (srcset) doesn't get swapped out for the image.  It seems like the javascript occasionally doesn't fire.  I've seen this on a few recent versions of Chrome 5x, but haven't tried rolling back to 49.xx or earlier.

I've whipped up a simple test page.  Just load up Chrome and scroll down as normal and wait for a row of blank images.  If you scroll them out of view and back into view, they then load.
https://www.harpgallery.com/test.html

Maybe it's a Chrome bug?

**Comment by ivopetkov** [comment]
I've run your test page on Chrome 53 on Windows 10 and images load just fine. Can you please tell me what your OS is.

There is something interesting about Responsively Lazy on Chrome. In Chrome there is a new API called IntersectionObserver that is used to detect if an image is visible. In your test case, it can skip some images in the middle rows if you scroll too fast, but the images that are currently visible should always load.

**Comment by dleer** [comment]
Thanks for taking a look at this.   It is Chrome 53 for Windows, mouse scrolling the page gradually from top to bottom.  You may need to scroll through the page twice but it will happen. A row of 3 images still showing the transparent blank image.   

Since you asked about OS, I also tried Chrome on Android and it did manifest there as well.  Though on Android slightly scrolling the screen causes the photos to load. On Windows you need to scroll the unloaded row off the screen and then back.

![clipboard01](https://cloud.githubusercontent.com/assets/12356696/18484016/4fadca84-79ac-11e6-918f-a5b2604677f8.jpg)
![screenshot_2016-09-13-12-21-30](https://cloud.githubusercontent.com/assets/12356696/18484131/c8793674-79ac-11e6-8747-ced34c758c83.jpg)

**Comment by ivopetkov** [comment]
Is there something related to the problem in the console or failed requests in the network tab in the Dev tools?

**Comment by dleer** [comment]
The error console is blank and network shows all code 200 in the transfers.   I also disabled the network connection and let it load entirely from local cache and it still had a blank row (and recovered upon scrolling back over the missing images).  And then I cleared the cache, enabled network, and loaded the page with the same behavior.

**Comment by ivopetkov** [comment]
Hello again. I've checked you demo one more time and again it works great. I've also checked the Chrome bug tracker for related issues and did not found any. Do you still encounter the problem?

**Comment by fireform** [comment]
Hi,
First off, thanks for your huge work on this plugin! I'm experiencing the same issue on Chrome. It happens when visit the same page a few times. The problem is in browser caching, I believe. No problems at all with disabled cache. So you need to scroll second time to get image visible. Maybe a second check after a few seconds or testing for already cached images may help? I'm not familiar with IntersectionObserver so I'm not sure where to dig. Thanks in advance!

P.S. It looks like API does work good in [tests](https://codepen.io/chrisux/pen/KrOYdo)

**Comment by fireform** [comment]
As a temporary solution I disabled Intersection Observer checks (hasIntersectionObserverSupport = false;) and it seems now works correctly using 'scroll' event. What do you think? Thanks!

**Comment by ivopetkov** [comment]
A second check sounds like a good solution. I'll add it soon.

**Comment by ivopetkov** [comment]
Ok, guys, there is a new release (v2.0.2) that I believe fixes the issues with the missing images.
