### ISSUE TITLE
It would have been nice to be able to add an offset, to load images earlier.

### ISSUE THREAD

**Issue by konrad-j** [ivopetkov/responsively-lazy#14]
In Chrome for mobile images are loaded very slow, 1-2 sec when the page have many images. Even if the images are in local cache.

**Comment by ivopetkov** [comment]
I agree. Do you have any ideas for the configuration?

**Comment by konrad-j** [comment]
What about adding a config array before loading responsively-lazy, or a function to set config values after? Then we can set a offset in pixels, value 500 will start to loading an image 500 pixels before it enters the viewport.

**Comment by ivopetkov** [comment]
Threshold support is added in v3.0 🎉
