### ISSUE TITLE
no-script not working

### ISSUE THREAD

**Issue by WebsiteRob** [ivopetkov/responsively-lazy#16]
Howdy,

Did some testing and found with JS disabled within the Browser, no images will show.

Windows 7  64bit
Firefox 53.0.2
Opera 45

I can get image to show if "srcset" attribute is removed.

Other than that it looks like a nice script you've put together. Kudos for providing it open source with MIT Licensing.

**Comment by ivopetkov** [comment]
Yes, that's correct. The library requires JavaScript. If you really need support for disabled JS I'd recommend adding `<noscript><img src="myimage.jpg"></noscript>`.
