### ISSUE TITLE
What about threshold?

### ISSUE THREAD

**Issue by vadimilyin** [ivopetkov/responsively-lazy#17]
But before you will add this setting, maybe I can make it manually on mi site?

**Comment by vadimilyin** [comment]
I guess I can add threshold on the line 159.
windowHeight = window.innerHeight + threshold;

or just multiply by 2 for extra screen threshold.
windowHeight = window.innerHeight*2;

Am I right?

**Comment by vadimilyin** [comment]
To detect the correct window height on mobile devices:
(window.innerHeight?window.innerHeight:$window.height())*threshold

**Comment by ivopetkov** [comment]
Threshold support is added in v3.0 🎉
