### ISSUE TITLE
Google Bot prefers scrset over src

### ISSUE THREAD

**Issue by tawgul** [ivopetkov/responsively-lazy#18]
Hi Ivo.
It is not an issues but I'd like to mention that Google bot uses `scrset ` over `src` and executes JS of course.
So Google bot will not use the default large image in `src` but will use the one inserted into `srcset`.

**Comment by ivopetkov** [comment]
It may be true, but I've found no issues with Google indexing the image in the `src` attribute. And I haven't seen an indexed image from the 'data-src' attribute yet. The library works as advertised :)
