### ISSUE TITLE
Lazy load Instagram Images - Instagram Api display

### ISSUE THREAD

**Issue by skigo** [ivopetkov/responsively-lazy#23]
Hello,

I am looking a way to lazy load the images from instagram basic display api.

I use the code:
`<img class="instagram-feed__item__image" data-src="<?php echo $image_url; ?>" alt="<?php echo $item['caption']; ?>" class="responsively-lazy">`

But the Image url is like: https://scontent.cdninstagram.com/v/t51.29350-15/133049651_2767029926897156_3167520314147899187_n.jpg?_nc_cat=105&ccb=2&_nc_sid=8ae9d6&_nc_ohc=LbOZsO0i_PsAX_swsGB&_nc_ht=scontent.cdninstagram.com&oh=d7ca6bd41c09130304ad5e6b760a9889&oe=60137C1B

Any idea how to apply lazy load?

Regards,
Dimitris

**Comment by ivopetkov** [comment]
Version 3.0 is now released 🎉
Please take a look at new API.
