### ISSUE TITLE
Horizontal scroll and unknown image aspect ratio

### ISSUE THREAD

**Issue by dacz** [ivopetkov/responsively-lazy#3]
Hi, does it work in horizontally scrollable element when I do not know image aspect ratio?
I have 50 small images, different image aspect ratio on page with horizontal scrolling.
In total they have 250kB and they are 50 requests.
Thanks!

**Comment by ivopetkov** [comment]
It works only if the scrollable element is the body. Is this your case?

**Comment by aFarkas** [comment]
@ivopetkov 
I think his problem is, that initially all images are in viewport, because they have a width of 0. You maybe can fix this by adding a min-width to your images?

Beside this on all browsers but blink/webkit it is the html element that scrolls. See also this: https://dev.opera.com/articles/fixing-the-scrolltop-bug/

This was fixed in Chrome 47 (or 46).

**Comment by dacz** [comment]
Exactly as wrote @aFarkas: when width is not specified, they are all visible (once the element is in viewport.

I would like to solve this: http://origamica.com at the very bottom. The whole wide div is loaded with ajax and only a couple of images are visible. I'd need lazy loaded images in this stripe. Submitting the sizes would be compicated because most have different sizes and are added by script.

Thanks.

**Comment by ivopetkov** [comment]
The following updates could be made:
1. Make the library work in elements with overflow (not only the body). This should be easy.
2. Currently, the available space is calculated using the width of the image container. There should be a way to use the height.

.. but I don't think there is a way to make it work in origamica's case. If you don't know the width or the aspect ratio of the images, the horizontal scrollbar will not be visible, or will resize during scrolling (which is bad user experience).

**Comment by dacz** [comment]
ad 1. I think that it would help a lot and be big benefit for the library. Would be nice to be able to defer loading images even before the the div is visible (I think lazy load xt has something like this - even lazy load scripts).

ad 2. I do not understand quite well, sorry.

... you are right about bad user experience, it did not come on my mind. I think that resized scrollbar is not so big deal (we all are accustomed to resizing vertical scrollbar in infinite scrolling) but users will not be able to scroll more than one (unloaded) image and that's bad.

Ok, it makes sense to change the workflow on my side to submit sizes to images.

So I will know width (each picture different) and height (in my case all imgs have the same height) and I can get it into html (is there standard width/height method instead of ratio?).

Then... is it possible to make it working in my case?

Thanks @ivopetkov for help and great library!

**Comment by ivopetkov** [comment]
The first update will make it work in your case.

You can use `padding-bottom: calc((imageHeight / imageWidth) * 100%)` instead of `padding-bottom:aspectRatio%` but it's support is [81.25%](http://caniuse.com/#feat=calc).
