### ISSUE TITLE
Re-running after DOM changes

### ISSUE THREAD

**Issue by mcky** [ivopetkov/responsively-lazy#4]
For this project we've got to cycle through a series of images (a series of `<img>` tags in a container, cycling through them toggling a `hidden` class)

What I can't figure out is how to re-run responsively-lazy against the new elements (which were hidden when it ran). I've tried playing around with a browserified version and trying to make it re-initializable but haven't had much luck.

**Comment by ivopetkov** [comment]
You can call `responsivelyLazy.run()` and all new visible elements will be loaded.

**Comment by phun-ky** [comment]
@ivopetkov possible to add `responsivelyLazy.run()` and the usage in the README.md?

**Comment by ivopetkov** [comment]
Great idea. Just added it.
