### ISSUE TITLE
ie 11 and responsively-lazy height

### ISSUE THREAD

**Issue by deepaksp** [ivopetkov/responsively-lazy#5]
Well today I checked my website on ie 11 and it was not working I mean I couldn't see images.
Turn out to be img.responsively-lazy height was 0 and ie was unable to run your JS I guess where it overwrites height.

so I removed height:0 and now its working fine.

Any specific reason for height 0 ??

**Comment by ivopetkov** [comment]
Do you have the code running online so I can see the problem?

**Comment by deepaksp** [comment]
you can check here @ivopetkov 

https://www.picsinhd.com/gitTest

**Comment by ivopetkov** [comment]
Removing "height:0" looks like the best solution. I've just updated the repo. Thank you.
