### ISSUE TITLE
responsively-lazy and Bootstrap сarousel

### ISSUE THREAD

**Issue by Avatar4eg** [ivopetkov/responsively-lazy#8]
Is there a way to load images in Bootstrap carousel when it start rotating?
For now i use:
`$('.carousel').each(function () {
            $(this).on('slid.bs.carousel', function () {
                responsivelyLazy.run();
            });
        });`
But it start loading only when rotation stops.
`slide.bs.carousel` not an option - image is still hidden.

**Comment by ivopetkov** [comment]
There is a brand new version (with the same API) in the master branch that I think will work perfectly in your case. Can you please try it.

**Comment by Avatar4eg** [comment]
Hey. Thx for advice, but same result - by default image not loading, only with `carousel.on('slid.bs.carousel'...` and only when rotation stops.

**Comment by ivopetkov** [comment]
I've checked the Bootstrap сarousel library and calling `responsivelyLazy.run()` is the only solution because the carousel uses `display:none` for the invisible slides. You can try the `slide.bs.carousel` event also.
